version: '2.2'

services:
  web:
    container_name: BasicPortfolio
    restart: always
    build: ./.docker
    ports:
      - 80:8080
    networks:
      - overlay
    volumes:
      - /var/Docker/BasicPortfolio/:/app

networks:
  overlay:
