FROM node:24.19.0-alpine

WORKDIR /app

# Copiamos solo archivos de dependencias primero para aprovechar la cache
COPY package*.json ./

RUN npm install

# Copiamos el resto del código
COPY . .

# Exponemos el puerto por defecto de Astro
EXPOSE 4321

# Comando para desarrollo
CMD ["npm", "run", "dev"]
